using Microsoft.EntityFrameworkCore;
using MKSANCrud.Data;

namespace MKSANCrud.Services.Database;

public sealed class DatabaseSchemaV13Initializer
{
    private readonly MKSANContext _context;
    private readonly ILogger<DatabaseSchemaV13Initializer> _logger;

    public DatabaseSchemaV13Initializer(
        MKSANContext context,
        ILogger<DatabaseSchemaV13Initializer> logger)
    {
        _context = context;
        _logger = logger;
    }

    public async Task AplicarAsync(CancellationToken ct = default)
    {
        var sql = """
            CREATE TABLE IF NOT EXISTS "ConversasAtendimento" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "PacienteId" integer NULL,
                "Canal" character varying(20) NOT NULL,
                "IdentificadorExterno" character varying(320) NOT NULL,
                "SessionId" character varying(160) NOT NULL,
                "Assunto" character varying(300) NULL,
                "Modo" character varying(20) NOT NULL DEFAULT 'IA',
                "ResponsavelUsuarioId" text NULL,
                "Ativa" boolean NOT NULL DEFAULT TRUE,
                "CriadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "AtualizadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "UltimaInteracaoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "AssumidaEm" timestamp with time zone NULL,
                "VisualizadaEm" timestamp with time zone NULL
            );

            CREATE UNIQUE INDEX IF NOT EXISTS
                "IX_ConversasAtendimento_Canal_IdentificadorExterno"
                ON "ConversasAtendimento"
                ("Canal", "IdentificadorExterno");

            CREATE INDEX IF NOT EXISTS
                "IX_ConversasAtendimento_PacienteId_UltimaInteracaoEm"
                ON "ConversasAtendimento"
                ("PacienteId", "UltimaInteracaoEm");

            CREATE INDEX IF NOT EXISTS
                "IX_ConversasAtendimento_ResponsavelUsuarioId"
                ON "ConversasAtendimento"
                ("ResponsavelUsuarioId");

            CREATE TABLE IF NOT EXISTS "MensagensAtendimento" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ConversaAtendimentoId" bigint NOT NULL,
                "Direcao" character varying(20) NOT NULL,
                "Autor" character varying(20) NOT NULL,
                "Status" character varying(20) NOT NULL,
                "MensagemExternaId" character varying(220) NULL,
                "Texto" character varying(5000) NOT NULL,
                "Erro" character varying(1000) NULL,
                "AutorUsuarioId" text NULL,
                "CriadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "EnviadoEm" timestamp with time zone NULL
            );

            CREATE INDEX IF NOT EXISTS
                "IX_MensagensAtendimento_ConversaAtendimentoId_CriadoEm"
                ON "MensagensAtendimento"
                ("ConversaAtendimentoId", "CriadoEm");

            CREATE UNIQUE INDEX IF NOT EXISTS
                "IX_MensagensAtendimento_ConversaAtendimentoId_MensagemExternaId"
                ON "MensagensAtendimento"
                ("ConversaAtendimentoId", "MensagemExternaId")
                WHERE "MensagemExternaId" IS NOT NULL;

            CREATE INDEX IF NOT EXISTS
                "IX_MensagensAtendimento_AutorUsuarioId"
                ON "MensagensAtendimento"
                ("AutorUsuarioId");

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname =
                        'FK_ConversasAtendimento_Pacientes_PacienteId'
                ) THEN
                    ALTER TABLE "ConversasAtendimento"
                    ADD CONSTRAINT
                        "FK_ConversasAtendimento_Pacientes_PacienteId"
                    FOREIGN KEY ("PacienteId")
                    REFERENCES "Pacientes"("Id")
                    ON DELETE SET NULL;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname =
                        'FK_ConversasAtendimento_AspNetUsers_ResponsavelUsuarioId'
                ) THEN
                    ALTER TABLE "ConversasAtendimento"
                    ADD CONSTRAINT
                        "FK_ConversasAtendimento_AspNetUsers_ResponsavelUsuarioId"
                    FOREIGN KEY ("ResponsavelUsuarioId")
                    REFERENCES "AspNetUsers"("Id")
                    ON DELETE SET NULL;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname =
                        'FK_MensagensAtendimento_ConversasAtendimento_ConversaAtendimentoId'
                ) THEN
                    ALTER TABLE "MensagensAtendimento"
                    ADD CONSTRAINT
                        "FK_MensagensAtendimento_ConversasAtendimento_ConversaAtendimentoId"
                    FOREIGN KEY ("ConversaAtendimentoId")
                    REFERENCES "ConversasAtendimento"("Id")
                    ON DELETE CASCADE;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname =
                        'FK_MensagensAtendimento_AspNetUsers_AutorUsuarioId'
                ) THEN
                    ALTER TABLE "MensagensAtendimento"
                    ADD CONSTRAINT
                        "FK_MensagensAtendimento_AspNetUsers_AutorUsuarioId"
                    FOREIGN KEY ("AutorUsuarioId")
                    REFERENCES "AspNetUsers"("Id")
                    ON DELETE SET NULL;
                END IF;
            END $$;
            """;

        try
        {
            await _context.Database.ExecuteSqlRawAsync(
                sql,
                ct);

            _logger.LogInformation(
                "Patch de schema V13 (atendimento multicanal) aplicado/verificado.");
        }
        catch (Exception ex)
        {
            _logger.LogError(
                ex,
                "Falha ao aplicar o patch V13 de atendimento multicanal.");
            throw;
        }
    }
}
