using Microsoft.EntityFrameworkCore;
using MKSANCrud.Data;

namespace MKSANCrud.Services.Database;

public sealed class DatabaseSchemaV15Initializer
{
    private readonly MKSANContext _context;
    private readonly ILogger<DatabaseSchemaV15Initializer> _logger;

    public DatabaseSchemaV15Initializer(MKSANContext context, ILogger<DatabaseSchemaV15Initializer> logger)
    {
        _context = context;
        _logger = logger;
    }

    public async Task AplicarAsync(CancellationToken ct = default)
    {
        var sql = """
            ALTER TABLE "Medicos" ADD COLUMN IF NOT EXISTS "UsuarioId" text NULL;
            ALTER TABLE "Medicos" ADD COLUMN IF NOT EXISTS "Email" character varying(256) NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Medicos_UsuarioId" ON "Medicos" ("UsuarioId") WHERE "UsuarioId" IS NOT NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Medicos_Email" ON "Medicos" ("Email") WHERE "Email" IS NOT NULL;

            DO $$ BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_Medicos_AspNetUsers_UsuarioId') THEN
                    ALTER TABLE "Medicos" ADD CONSTRAINT "FK_Medicos_AspNetUsers_UsuarioId"
                    FOREIGN KEY ("UsuarioId") REFERENCES "AspNetUsers"("Id") ON DELETE SET NULL;
                END IF;
            END $$;

            CREATE TABLE IF NOT EXISTS "ListasEspera" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "PacienteId" integer NOT NULL,
                "MedicoId" integer NULL,
                "EspecialidadeId" integer NULL,
                "DataPreferida" date NULL,
                "Periodo" character varying(20) NOT NULL DEFAULT 'Qualquer',
                "Observacao" character varying(500) NULL,
                "Ativa" boolean NOT NULL DEFAULT TRUE,
                "CriadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "AtualizadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "NotificadoEm" timestamp with time zone NULL,
                "UltimaDisponibilidadeId" integer NULL
            );

            CREATE INDEX IF NOT EXISTS "IX_ListasEspera_Ativa_CriadoEm" ON "ListasEspera" ("Ativa", "CriadoEm");
            CREATE INDEX IF NOT EXISTS "IX_ListasEspera_PacienteId" ON "ListasEspera" ("PacienteId");
            CREATE INDEX IF NOT EXISTS "IX_ListasEspera_MedicoId" ON "ListasEspera" ("MedicoId");
            CREATE INDEX IF NOT EXISTS "IX_ListasEspera_EspecialidadeId" ON "ListasEspera" ("EspecialidadeId");

            DO $$ BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_ListasEspera_Pacientes_PacienteId') THEN
                    ALTER TABLE "ListasEspera" ADD CONSTRAINT "FK_ListasEspera_Pacientes_PacienteId" FOREIGN KEY ("PacienteId") REFERENCES "Pacientes"("Id") ON DELETE CASCADE;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_ListasEspera_Medicos_MedicoId') THEN
                    ALTER TABLE "ListasEspera" ADD CONSTRAINT "FK_ListasEspera_Medicos_MedicoId" FOREIGN KEY ("MedicoId") REFERENCES "Medicos"("Id") ON DELETE SET NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_ListasEspera_Especialidades_EspecialidadeId') THEN
                    ALTER TABLE "ListasEspera" ADD CONSTRAINT "FK_ListasEspera_Especialidades_EspecialidadeId" FOREIGN KEY ("EspecialidadeId") REFERENCES "Especialidades"("Id") ON DELETE SET NULL;
                END IF;
            END $$;

            ALTER TABLE "Disponibilidades" ADD COLUMN IF NOT EXISTS "BloqueioManual" boolean NOT NULL DEFAULT FALSE;

            ALTER TABLE "Consultas" ADD COLUMN IF NOT EXISTS "Lembrete24hEnviadoEm" timestamp with time zone NULL;
            ALTER TABLE "Consultas" ADD COLUMN IF NOT EXISTS "Lembrete2hEnviadoEm" timestamp with time zone NULL;
            """;

        await _context.Database.ExecuteSqlRawAsync(sql, ct);
        _logger.LogInformation("Patch V15 (área médica, lembretes e lista de espera) aplicado/verificado.");
    }
}
