using Microsoft.EntityFrameworkCore;
using MKSANCrud.Data;

namespace MKSANCrud.Services.Database;

public sealed class DatabaseSchemaV22Initializer(MKSANContext context)
{
    public Task AplicarAsync(CancellationToken ct = default) => context.Database.ExecuteSqlRawAsync("""
        ALTER TABLE "Pacientes" ALTER COLUMN "Email" DROP NOT NULL;
        UPDATE "Pacientes" SET "Email" = NULL WHERE btrim("Email") = '' AND "UsuarioId" IS NULL;
        ALTER TABLE "SolicitacoesAtendimento" ADD COLUMN IF NOT EXISTS "ChaveContingencia" uuid NULL;
        ALTER TABLE "SolicitacoesAtendimento" ADD COLUMN IF NOT EXISTS "RecebidaNoServidorEm" timestamp with time zone NULL;
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_SolicitacoesAtendimento_ChaveContingencia"
            ON "SolicitacoesAtendimento" ("ChaveContingencia");
        CREATE TABLE IF NOT EXISTS "ExamesHistorico" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "PacienteId" integer NOT NULL REFERENCES "Pacientes"("Id") ON DELETE RESTRICT,
            "Nome" character varying(160) NOT NULL,
            "DataRealizacao" date NOT NULL,
            "LocalRealizacao" character varying(160) NULL,
            "Ativo" boolean NOT NULL DEFAULT TRUE,
            "CriadoEm" timestamp with time zone NOT NULL DEFAULT now()
        );
        CREATE INDEX IF NOT EXISTS "IX_ExamesHistorico_PacienteId_DataRealizacao"
            ON "ExamesHistorico" ("PacienteId", "DataRealizacao");
        """, ct);
}
