using Microsoft.EntityFrameworkCore;
using MKSANCrud.Data;

namespace MKSANCrud.Services.Database;

public sealed class DatabaseSchemaV12Initializer
{
    private readonly MKSANContext _context;
    private readonly ILogger<DatabaseSchemaV12Initializer> _logger;

    public DatabaseSchemaV12Initializer(
        MKSANContext context,
        ILogger<DatabaseSchemaV12Initializer> logger)
    {
        _context = context;
        _logger = logger;
    }

    public async Task AplicarAsync(CancellationToken ct = default)
    {
        // Patch idempotente para bancos Neon já existentes cujo histórico de
        // migrations não corresponde integralmente ao projeto local.
        // Apenas acrescenta elementos necessários à V12 quando ainda não existem.
        var sql = """
            ALTER TABLE "Pacientes"
                ADD COLUMN IF NOT EXISTS "UsuarioId" text;

            ALTER TABLE "Pacientes"
                ADD COLUMN IF NOT EXISTS "Ativo" boolean NOT NULL DEFAULT TRUE;

            ALTER TABLE "Funcionarios"
                ADD COLUMN IF NOT EXISTS "UsuarioId" text;

            CREATE TABLE IF NOT EXISTS "Especialidades" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Nome" character varying(100) NOT NULL,
                "Ativo" boolean NOT NULL DEFAULT TRUE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Especialidades_Nome"
                ON "Especialidades" ("Nome");

            ALTER TABLE "Medicos"
                ADD COLUMN IF NOT EXISTS "EspecialidadeId" integer;

            CREATE INDEX IF NOT EXISTS "IX_Medicos_EspecialidadeId"
                ON "Medicos" ("EspecialidadeId");

            CREATE TABLE IF NOT EXISTS "ConversasAgente" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UsuarioId" text NOT NULL,
                "SessionId" character varying(120) NOT NULL,
                "CriadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "AtualizadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ConversasAgente_UsuarioId_SessionId"
                ON "ConversasAgente" ("UsuarioId", "SessionId");

            CREATE TABLE IF NOT EXISTS "MensagensAgente" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ConversaAgenteId" integer NOT NULL,
                "Papel" character varying(20) NOT NULL,
                "Texto" character varying(2000) NOT NULL,
                "CriadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE INDEX IF NOT EXISTS "IX_MensagensAgente_ConversaAgenteId_CriadoEm"
                ON "MensagensAgente" ("ConversaAgenteId", "CriadoEm");

            -- Normaliza os estados legados antes de aplicar regras e índices.
            UPDATE "Consultas" SET "Status" = 'Pendente' WHERE lower("Status") = 'pendente';
            UPDATE "Consultas" SET "Status" = 'Confirmada' WHERE lower("Status") IN ('confirmada', 'confirmado');
            UPDATE "Consultas" SET "Status" = 'Remarcada' WHERE lower("Status") IN ('remarcada', 'remarcado');
            UPDATE "Consultas" SET "Status" = 'Cancelada' WHERE lower("Status") IN ('cancelada', 'cancelado');
            UPDATE "Consultas" SET "Status" = 'Realizada' WHERE lower("Status") IN ('realizada', 'realizado');

            UPDATE "Pacientes" p
            SET "UsuarioId" = u."Id"
            FROM "AspNetUsers" u
            WHERE p."UsuarioId" IS NULL
              AND u."Email" IS NOT NULL
              AND lower(p."Email") = lower(u."Email");

            UPDATE "Funcionarios" f
            SET "UsuarioId" = u."Id"
            FROM "AspNetUsers" u
            WHERE f."UsuarioId" IS NULL
              AND u."Email" IS NOT NULL
              AND lower(f."Email") = lower(u."Email");

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Pacientes_UsuarioId"
                ON "Pacientes" ("UsuarioId")
                WHERE "UsuarioId" IS NOT NULL;

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Funcionarios_UsuarioId"
                ON "Funcionarios" ("UsuarioId")
                WHERE "UsuarioId" IS NOT NULL;

            CREATE INDEX IF NOT EXISTS "IX_Consultas_PacienteId_Data"
                ON "Consultas" ("PacienteId", "Data");

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_indexes
                    WHERE schemaname = current_schema()
                      AND indexname = 'IX_Consultas_Slot_Ativo'
                )
                AND NOT EXISTS (
                    SELECT 1
                    FROM "Consultas"
                    WHERE lower("Status") <> 'cancelada'
                    GROUP BY "MedicoId", "Data", "Horario"
                    HAVING COUNT(*) > 1
                ) THEN
                    EXECUTE 'CREATE UNIQUE INDEX "IX_Consultas_Slot_Ativo" ON "Consultas" ("MedicoId", "Data", "Horario") WHERE lower("Status") <> ''cancelada''';
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'FK_Pacientes_AspNetUsers_UsuarioId'
                ) THEN
                    ALTER TABLE "Pacientes"
                    ADD CONSTRAINT "FK_Pacientes_AspNetUsers_UsuarioId"
                    FOREIGN KEY ("UsuarioId") REFERENCES "AspNetUsers"("Id")
                    ON DELETE SET NULL;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'FK_Funcionarios_AspNetUsers_UsuarioId'
                ) THEN
                    ALTER TABLE "Funcionarios"
                    ADD CONSTRAINT "FK_Funcionarios_AspNetUsers_UsuarioId"
                    FOREIGN KEY ("UsuarioId") REFERENCES "AspNetUsers"("Id")
                    ON DELETE SET NULL;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'FK_Medicos_Especialidades_EspecialidadeId'
                ) THEN
                    ALTER TABLE "Medicos"
                    ADD CONSTRAINT "FK_Medicos_Especialidades_EspecialidadeId"
                    FOREIGN KEY ("EspecialidadeId") REFERENCES "Especialidades"("Id")
                    ON DELETE RESTRICT;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'FK_ConversasAgente_AspNetUsers_UsuarioId'
                ) THEN
                    ALTER TABLE "ConversasAgente"
                    ADD CONSTRAINT "FK_ConversasAgente_AspNetUsers_UsuarioId"
                    FOREIGN KEY ("UsuarioId") REFERENCES "AspNetUsers"("Id")
                    ON DELETE CASCADE;
                END IF;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'FK_MensagensAgente_ConversasAgente_ConversaAgenteId'
                ) THEN
                    ALTER TABLE "MensagensAgente"
                    ADD CONSTRAINT "FK_MensagensAgente_ConversasAgente_ConversaAgenteId"
                    FOREIGN KEY ("ConversaAgenteId") REFERENCES "ConversasAgente"("Id")
                    ON DELETE CASCADE;
                END IF;
            END $$;
            """;

        try
        {
            await _context.Database.ExecuteSqlRawAsync(sql, ct);

            var indiceSlotAtivo = await _context.Database
                .SqlQueryRaw<bool>(
                    "SELECT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = current_schema() AND indexname = 'IX_Consultas_Slot_Ativo') AS \"Value\"")
                .SingleAsync(ct);

            if (!indiceSlotAtivo)
            {
                _logger.LogWarning(
                    "O índice único de slots ativos não foi criado porque o banco já possui consultas ativas duplicadas. Corrija as duplicidades; a V12 ainda usa advisory lock para impedir novas corridas.");
            }

            _logger.LogInformation("Patch de schema V12 aplicado/verificado.");
        }
        catch (Exception ex)
        {
            _logger.LogError(
                ex,
                "Falha ao aplicar o patch de schema V12. Defina Database__ApplyV12Patch=false apenas se o schema já tiver sido atualizado manualmente.");
            throw;
        }
    }
}
