using Microsoft.EntityFrameworkCore;
using MKSANCrud.Data;

namespace MKSANCrud.Services.Database;

public sealed class DatabaseSchemaV16Initializer
{
    private readonly MKSANContext _context;
    private readonly ILogger<DatabaseSchemaV16Initializer> _logger;

    public DatabaseSchemaV16Initializer(
        MKSANContext context,
        ILogger<DatabaseSchemaV16Initializer> logger)
    {
        _context = context;
        _logger = logger;
    }

    public async Task AplicarAsync(CancellationToken ct = default)
    {
        var sql = """
            CREATE TABLE IF NOT EXISTS "AgendaExcecoes" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "MedicoId" integer NOT NULL,
                "Tipo" character varying(20) NOT NULL,
                "Data" date NOT NULL,
                "HorarioInicio" character varying(5) NULL,
                "HorarioFim" character varying(5) NULL,
                "Motivo" character varying(300) NULL,
                "Ativa" boolean NOT NULL DEFAULT TRUE,
                "CriadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "EncerradoEm" timestamp with time zone NULL
            );

            CREATE INDEX IF NOT EXISTS "IX_AgendaExcecoes_MedicoId_Data_Ativa"
                ON "AgendaExcecoes" ("MedicoId", "Data", "Ativa");

            DO $$ BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_AgendaExcecoes_Medicos_MedicoId') THEN
                    ALTER TABLE "AgendaExcecoes"
                    ADD CONSTRAINT "FK_AgendaExcecoes_Medicos_MedicoId"
                    FOREIGN KEY ("MedicoId") REFERENCES "Medicos"("Id") ON DELETE CASCADE;
                END IF;
            END $$;

            ALTER TABLE "Disponibilidades"
                ADD COLUMN IF NOT EXISTS "AgendaExcecaoId" integer NULL;

            CREATE INDEX IF NOT EXISTS "IX_Disponibilidades_AgendaExcecaoId"
                ON "Disponibilidades" ("AgendaExcecaoId");

            DO $$ BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_Disponibilidades_AgendaExcecoes_AgendaExcecaoId') THEN
                    ALTER TABLE "Disponibilidades"
                    ADD CONSTRAINT "FK_Disponibilidades_AgendaExcecoes_AgendaExcecaoId"
                    FOREIGN KEY ("AgendaExcecaoId") REFERENCES "AgendaExcecoes"("Id") ON DELETE SET NULL;
                END IF;
            END $$;
            """;

        await _context.Database.ExecuteSqlRawAsync(sql, ct);
        _logger.LogInformation("Patch V16 (exceções da agenda) aplicado/verificado.");
    }
}
