using Microsoft.EntityFrameworkCore;
using MKSANCrud.Data;

namespace MKSANCrud.Services.Database;

public sealed class DatabaseSchemaV21Initializer
{
    private readonly MKSANContext _context;
    private readonly ILogger<DatabaseSchemaV21Initializer> _logger;

    public DatabaseSchemaV21Initializer(MKSANContext context, ILogger<DatabaseSchemaV21Initializer> logger)
    {
        _context = context;
        _logger = logger;
    }

    public async Task AplicarAsync(CancellationToken ct = default)
    {
        var sql = """
            ALTER TABLE "Pacientes"
                ADD COLUMN IF NOT EXISTS "CanalPreferido" character varying(20) NOT NULL DEFAULT 'WhatsApp';

            ALTER TABLE "Consultas"
                ADD COLUMN IF NOT EXISTS "ConfirmadaEm" timestamp with time zone NULL;
            ALTER TABLE "Consultas"
                ADD COLUMN IF NOT EXISTS "CanceladaEm" timestamp with time zone NULL;
            ALTER TABLE "Consultas"
                ADD COLUMN IF NOT EXISTS "RealizadaEm" timestamp with time zone NULL;
            ALTER TABLE "Consultas"
                ADD COLUMN IF NOT EXISTS "AusenteEm" timestamp with time zone NULL;

            CREATE TABLE IF NOT EXISTS "ConveniosEspecialidades" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ConvenioNome" character varying(120) NOT NULL,
                "ConvenioChave" character varying(160) NOT NULL,
                "EspecialidadeId" integer NOT NULL,
                "Coberta" boolean NOT NULL DEFAULT TRUE,
                "Ativo" boolean NOT NULL DEFAULT TRUE,
                "Observacao" character varying(500) NULL,
                "CriadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "AtualizadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ConveniosEspecialidades_ConvenioChave_EspecialidadeId"
                ON "ConveniosEspecialidades" ("ConvenioChave", "EspecialidadeId");

            DO $$ BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_ConveniosEspecialidades_Especialidades_EspecialidadeId') THEN
                    ALTER TABLE "ConveniosEspecialidades"
                    ADD CONSTRAINT "FK_ConveniosEspecialidades_Especialidades_EspecialidadeId"
                    FOREIGN KEY ("EspecialidadeId") REFERENCES "Especialidades"("Id") ON DELETE CASCADE;
                END IF;
            END $$;

            CREATE TABLE IF NOT EXISTS "SolicitacoesAtendimento" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "PacienteId" integer NULL,
                "EspecialidadeId" integer NULL,
                "MedicoId" integer NULL,
                "ConsultaId" integer NULL,
                "ConversaAtendimentoId" bigint NULL,
                "Canal" character varying(20) NOT NULL,
                "Status" character varying(30) NOT NULL DEFAULT 'Nova',
                "NomeContato" character varying(160) NULL,
                "TelefoneContato" character varying(40) NULL,
                "EmailContato" character varying(256) NULL,
                "ConvenioInformado" character varying(120) NULL,
                "ElegivelConvenio" boolean NULL,
                "PendenciaTriagem" character varying(600) NULL,
                "JustificativaLiberacao" character varying(600) NULL,
                "PeriodoPreferido" character varying(20) NOT NULL DEFAULT 'Qualquer',
                "DataPreferida" date NULL,
                "Observacao" character varying(1200) NULL,
                "ResponsavelUsuarioId" text NULL,
                "CriadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "AtualizadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                "TriadaEm" timestamp with time zone NULL,
                "AguardandoPacienteEm" timestamp with time zone NULL,
                "ConfirmadaEm" timestamp with time zone NULL,
                "EncerradaEm" timestamp with time zone NULL
            );

            ALTER TABLE "SolicitacoesAtendimento"
                ADD COLUMN IF NOT EXISTS "JustificativaLiberacao" character varying(600) NULL;

            CREATE INDEX IF NOT EXISTS "IX_SolicitacoesAtendimento_Status_CriadoEm"
                ON "SolicitacoesAtendimento" ("Status", "CriadoEm");
            CREATE INDEX IF NOT EXISTS "IX_SolicitacoesAtendimento_PacienteId_CriadoEm"
                ON "SolicitacoesAtendimento" ("PacienteId", "CriadoEm");
            CREATE INDEX IF NOT EXISTS "IX_SolicitacoesAtendimento_ConversaAtendimentoId"
                ON "SolicitacoesAtendimento" ("ConversaAtendimentoId");

            DO $$ BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_SolicitacoesAtendimento_Pacientes_PacienteId') THEN
                    ALTER TABLE "SolicitacoesAtendimento" ADD CONSTRAINT "FK_SolicitacoesAtendimento_Pacientes_PacienteId"
                    FOREIGN KEY ("PacienteId") REFERENCES "Pacientes"("Id") ON DELETE SET NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_SolicitacoesAtendimento_Especialidades_EspecialidadeId') THEN
                    ALTER TABLE "SolicitacoesAtendimento" ADD CONSTRAINT "FK_SolicitacoesAtendimento_Especialidades_EspecialidadeId"
                    FOREIGN KEY ("EspecialidadeId") REFERENCES "Especialidades"("Id") ON DELETE SET NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_SolicitacoesAtendimento_Medicos_MedicoId') THEN
                    ALTER TABLE "SolicitacoesAtendimento" ADD CONSTRAINT "FK_SolicitacoesAtendimento_Medicos_MedicoId"
                    FOREIGN KEY ("MedicoId") REFERENCES "Medicos"("Id") ON DELETE SET NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_SolicitacoesAtendimento_Consultas_ConsultaId') THEN
                    ALTER TABLE "SolicitacoesAtendimento" ADD CONSTRAINT "FK_SolicitacoesAtendimento_Consultas_ConsultaId"
                    FOREIGN KEY ("ConsultaId") REFERENCES "Consultas"("Id") ON DELETE SET NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_SolicitacoesAtendimento_ConversasAtendimento_ConversaAtendimentoId') THEN
                    ALTER TABLE "SolicitacoesAtendimento" ADD CONSTRAINT "FK_SolicitacoesAtendimento_ConversasAtendimento_ConversaAtendimentoId"
                    FOREIGN KEY ("ConversaAtendimentoId") REFERENCES "ConversasAtendimento"("Id") ON DELETE SET NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_SolicitacoesAtendimento_AspNetUsers_ResponsavelUsuarioId') THEN
                    ALTER TABLE "SolicitacoesAtendimento" ADD CONSTRAINT "FK_SolicitacoesAtendimento_AspNetUsers_ResponsavelUsuarioId"
                    FOREIGN KEY ("ResponsavelUsuarioId") REFERENCES "AspNetUsers"("Id") ON DELETE SET NULL;
                END IF;
            END $$;

            CREATE TABLE IF NOT EXISTS "AuditoriaEventos" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UsuarioId" text NULL,
                "UsuarioNome" character varying(180) NULL,
                "Acao" character varying(80) NOT NULL,
                "Entidade" character varying(80) NOT NULL,
                "EntidadeId" character varying(80) NULL,
                "Descricao" character varying(1200) NULL,
                "ValorAnterior" character varying(3000) NULL,
                "ValorNovo" character varying(3000) NULL,
                "Ip" character varying(64) NULL,
                "CriadoEm" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE INDEX IF NOT EXISTS "IX_AuditoriaEventos_CriadoEm" ON "AuditoriaEventos" ("CriadoEm");
            CREATE INDEX IF NOT EXISTS "IX_AuditoriaEventos_Entidade_EntidadeId_CriadoEm"
                ON "AuditoriaEventos" ("Entidade", "EntidadeId", "CriadoEm");

            DO $$ BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='FK_AuditoriaEventos_AspNetUsers_UsuarioId') THEN
                    ALTER TABLE "AuditoriaEventos" ADD CONSTRAINT "FK_AuditoriaEventos_AspNetUsers_UsuarioId"
                    FOREIGN KEY ("UsuarioId") REFERENCES "AspNetUsers"("Id") ON DELETE SET NULL;
                END IF;
            END $$;
            """;

        await _context.Database.ExecuteSqlRawAsync(sql, ct);
        _logger.LogInformation("Patch V21 (triagem, convênios, auditoria e absenteísmo) aplicado/verificado.");
    }
}
