using Microsoft.EntityFrameworkCore;
using MKSANCrud.Data;

namespace MKSANCrud.Services.Database;

public sealed class DatabaseSchemaV14Initializer
{
    private readonly MKSANContext _context;
    private readonly ILogger<DatabaseSchemaV14Initializer> _logger;

    public DatabaseSchemaV14Initializer(
        MKSANContext context,
        ILogger<DatabaseSchemaV14Initializer> logger)
    {
        _context = context;
        _logger = logger;
    }

    public async Task AplicarAsync(CancellationToken ct = default)
    {
        var sql = """
            ALTER TABLE "Disponibilidades"
                ADD COLUMN IF NOT EXISTS "OrigemAgendaSemanal"
                boolean NOT NULL DEFAULT FALSE;

            CREATE TABLE IF NOT EXISTS "MedicoHorariosSemanais" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "MedicoId" integer NOT NULL,
                "DiaSemana" integer NOT NULL,
                "Horario" character varying(5) NOT NULL,
                "Ativo" boolean NOT NULL DEFAULT TRUE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS
                "IX_MedicoHorariosSemanais_MedicoId_DiaSemana_Horario"
                ON "MedicoHorariosSemanais" ("MedicoId", "DiaSemana", "Horario");

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'FK_MedicoHorariosSemanais_Medicos_MedicoId'
                ) THEN
                    ALTER TABLE "MedicoHorariosSemanais"
                    ADD CONSTRAINT "FK_MedicoHorariosSemanais_Medicos_MedicoId"
                    FOREIGN KEY ("MedicoId") REFERENCES "Medicos"("Id")
                    ON DELETE CASCADE;
                END IF;
            END $$;

            DELETE FROM "Especialidades" e
            WHERE lower(e."Nome") = 'cardiologia'
              AND NOT EXISTS (
                  SELECT 1 FROM "Medicos" m
                  WHERE m."EspecialidadeId" = e."Id"
              );
            """;

        try
        {
            await _context.Database.ExecuteSqlRawAsync(sql, ct);
            _logger.LogInformation(
                "Patch V14 (CallMed + agenda semanal de médicos) aplicado/verificado.");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Falha ao aplicar patch V14.");
            throw;
        }
    }
}
